//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Lql.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Lql.Parsing {

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
internal partial class LqlParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, ASC=21, DESC=22, AND=23, OR=24, DISTINCT=25, 
		EXISTS=26, NULL=27, IS=28, NOT=29, IN=30, AS=31, CASE=32, WHEN=33, THEN=34, 
		ELSE=35, END=36, WITH=37, OVER=38, PARTITION=39, ORDER=40, BY=41, COALESCE=42, 
		EXTRACT=43, FROM=44, INTERVAL=45, CURRENT_DATE=46, DATE_TRUNC=47, ON=48, 
		PARAMETER=49, IDENT=50, INT=51, DECIMAL=52, STRING=53, COMMENT=54, WS=55, 
		ASTERISK=56;
	public const int
		RULE_program = 0, RULE_statement = 1, RULE_letStmt = 2, RULE_pipeExpr = 3, 
		RULE_expr = 4, RULE_windowSpec = 5, RULE_partitionClause = 6, RULE_orderClause = 7, 
		RULE_lambdaExpr = 8, RULE_qualifiedIdent = 9, RULE_argList = 10, RULE_arg = 11, 
		RULE_columnAlias = 12, RULE_arithmeticExpr = 13, RULE_arithmeticTerm = 14, 
		RULE_arithmeticFactor = 15, RULE_functionCall = 16, RULE_namedArg = 17, 
		RULE_logicalExpr = 18, RULE_andExpr = 19, RULE_atomicExpr = 20, RULE_comparison = 21, 
		RULE_existsExpr = 22, RULE_nullCheckExpr = 23, RULE_inExpr = 24, RULE_caseExpr = 25, 
		RULE_whenClause = 26, RULE_caseResult = 27, RULE_orderDirection = 28, 
		RULE_comparisonOp = 29;
	public static readonly string[] ruleNames = {
		"program", "statement", "letStmt", "pipeExpr", "expr", "windowSpec", "partitionClause", 
		"orderClause", "lambdaExpr", "qualifiedIdent", "argList", "arg", "columnAlias", 
		"arithmeticExpr", "arithmeticTerm", "arithmeticFactor", "functionCall", 
		"namedArg", "logicalExpr", "andExpr", "atomicExpr", "comparison", "existsExpr", 
		"nullCheckExpr", "inExpr", "caseExpr", "whenClause", "caseResult", "orderDirection", 
		"comparisonOp"
	};

	private static readonly string[] _LiteralNames = {
		null, "'let'", "'='", "'|>'", "'('", "')'", "'fn'", "','", "'=>'", "'.'", 
		"'+'", "'-'", "'||'", "'/'", "'%'", "'!='", "'<>'", "'<'", "'>'", "'<='", 
		"'>='", null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		"'*'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, "ASC", "DESC", "AND", 
		"OR", "DISTINCT", "EXISTS", "NULL", "IS", "NOT", "IN", "AS", "CASE", "WHEN", 
		"THEN", "ELSE", "END", "WITH", "OVER", "PARTITION", "ORDER", "BY", "COALESCE", 
		"EXTRACT", "FROM", "INTERVAL", "CURRENT_DATE", "DATE_TRUNC", "ON", "PARAMETER", 
		"IDENT", "INT", "DECIMAL", "STRING", "COMMENT", "WS", "ASTERISK"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Lql.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static LqlParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public LqlParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public LqlParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	internal partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(LqlParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 63;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 89509046888955986L) != 0)) {
				{
				{
				State = 60;
				statement();
				}
				}
				State = 65;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 66;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class StatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public LetStmtContext letStmt() {
			return GetRuleContext<LetStmtContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PipeExprContext pipeExpr() {
			return GetRuleContext<PipeExprContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 2, RULE_statement);
		try {
			State = 70;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__0:
				EnterOuterAlt(_localctx, 1);
				{
				State = 68;
				letStmt();
				}
				break;
			case T__3:
			case T__5:
			case CASE:
			case PARAMETER:
			case IDENT:
			case INT:
			case DECIMAL:
			case STRING:
			case ASTERISK:
				EnterOuterAlt(_localctx, 2);
				{
				State = 69;
				pipeExpr();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class LetStmtContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(LqlParser.IDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public PipeExprContext pipeExpr() {
			return GetRuleContext<PipeExprContext>(0);
		}
		public LetStmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_letStmt; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterLetStmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitLetStmt(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLetStmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LetStmtContext letStmt() {
		LetStmtContext _localctx = new LetStmtContext(Context, State);
		EnterRule(_localctx, 4, RULE_letStmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 72;
			Match(T__0);
			State = 73;
			Match(IDENT);
			State = 74;
			Match(T__1);
			State = 75;
			pipeExpr();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class PipeExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public PipeExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pipeExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterPipeExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitPipeExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPipeExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PipeExprContext pipeExpr() {
		PipeExprContext _localctx = new PipeExprContext(Context, State);
		EnterRule(_localctx, 6, RULE_pipeExpr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 77;
			expr();
			State = 82;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__2) {
				{
				{
				State = 78;
				Match(T__2);
				State = 79;
				expr();
				}
				}
				State = 84;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class ExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(LqlParser.IDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OVER() { return GetToken(LqlParser.OVER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public WindowSpecContext windowSpec() {
			return GetRuleContext<WindowSpecContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArgListContext argList() {
			return GetRuleContext<ArgListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PipeExprContext pipeExpr() {
			return GetRuleContext<PipeExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public QualifiedIdentContext qualifiedIdent() {
			return GetRuleContext<QualifiedIdentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LambdaExprContext lambdaExpr() {
			return GetRuleContext<LambdaExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CaseExprContext caseExpr() {
			return GetRuleContext<CaseExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(LqlParser.INT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DECIMAL() { return GetToken(LqlParser.DECIMAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASTERISK() { return GetToken(LqlParser.ASTERISK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(LqlParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PARAMETER() { return GetToken(LqlParser.PARAMETER, 0); }
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		ExprContext _localctx = new ExprContext(Context, State);
		EnterRule(_localctx, 8, RULE_expr);
		int _la;
		try {
			State = 115;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 85;
				Match(IDENT);
				State = 86;
				Match(T__3);
				State = 88;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 89790521932775504L) != 0)) {
					{
					State = 87;
					argList();
					}
				}

				State = 90;
				Match(T__4);
				State = 91;
				Match(OVER);
				State = 92;
				Match(T__3);
				State = 93;
				windowSpec();
				State = 94;
				Match(T__4);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 96;
				Match(IDENT);
				State = 97;
				Match(T__3);
				State = 99;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 89790521932775504L) != 0)) {
					{
					State = 98;
					argList();
					}
				}

				State = 101;
				Match(T__4);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 102;
				Match(IDENT);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 103;
				Match(T__3);
				State = 104;
				pipeExpr();
				State = 105;
				Match(T__4);
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 107;
				qualifiedIdent();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 108;
				lambdaExpr();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 109;
				caseExpr();
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 110;
				Match(INT);
				}
				break;
			case 9:
				EnterOuterAlt(_localctx, 9);
				{
				State = 111;
				Match(DECIMAL);
				}
				break;
			case 10:
				EnterOuterAlt(_localctx, 10);
				{
				State = 112;
				Match(ASTERISK);
				}
				break;
			case 11:
				EnterOuterAlt(_localctx, 11);
				{
				State = 113;
				Match(STRING);
				}
				break;
			case 12:
				EnterOuterAlt(_localctx, 12);
				{
				State = 114;
				Match(PARAMETER);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class WindowSpecContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PartitionClauseContext partitionClause() {
			return GetRuleContext<PartitionClauseContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public OrderClauseContext orderClause() {
			return GetRuleContext<OrderClauseContext>(0);
		}
		public WindowSpecContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_windowSpec; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterWindowSpec(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitWindowSpec(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitWindowSpec(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public WindowSpecContext windowSpec() {
		WindowSpecContext _localctx = new WindowSpecContext(Context, State);
		EnterRule(_localctx, 10, RULE_windowSpec);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 118;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==PARTITION) {
				{
				State = 117;
				partitionClause();
				}
			}

			State = 121;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ORDER) {
				{
				State = 120;
				orderClause();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class PartitionClauseContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PARTITION() { return GetToken(LqlParser.PARTITION, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BY() { return GetToken(LqlParser.BY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArgListContext argList() {
			return GetRuleContext<ArgListContext>(0);
		}
		public PartitionClauseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_partitionClause; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterPartitionClause(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitPartitionClause(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPartitionClause(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PartitionClauseContext partitionClause() {
		PartitionClauseContext _localctx = new PartitionClauseContext(Context, State);
		EnterRule(_localctx, 12, RULE_partitionClause);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 123;
			Match(PARTITION);
			State = 124;
			Match(BY);
			State = 125;
			argList();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class OrderClauseContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ORDER() { return GetToken(LqlParser.ORDER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BY() { return GetToken(LqlParser.BY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArgListContext argList() {
			return GetRuleContext<ArgListContext>(0);
		}
		public OrderClauseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_orderClause; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterOrderClause(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitOrderClause(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOrderClause(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OrderClauseContext orderClause() {
		OrderClauseContext _localctx = new OrderClauseContext(Context, State);
		EnterRule(_localctx, 14, RULE_orderClause);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 127;
			Match(ORDER);
			State = 128;
			Match(BY);
			State = 129;
			argList();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class LambdaExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] IDENT() { return GetTokens(LqlParser.IDENT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT(int i) {
			return GetToken(LqlParser.IDENT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprContext logicalExpr() {
			return GetRuleContext<LogicalExprContext>(0);
		}
		public LambdaExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_lambdaExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterLambdaExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitLambdaExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLambdaExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LambdaExprContext lambdaExpr() {
		LambdaExprContext _localctx = new LambdaExprContext(Context, State);
		EnterRule(_localctx, 16, RULE_lambdaExpr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 131;
			Match(T__5);
			State = 132;
			Match(T__3);
			State = 133;
			Match(IDENT);
			State = 138;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__6) {
				{
				{
				State = 134;
				Match(T__6);
				State = 135;
				Match(IDENT);
				}
				}
				State = 140;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 141;
			Match(T__4);
			State = 142;
			Match(T__7);
			State = 143;
			logicalExpr();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class QualifiedIdentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] IDENT() { return GetTokens(LqlParser.IDENT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT(int i) {
			return GetToken(LqlParser.IDENT, i);
		}
		public QualifiedIdentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_qualifiedIdent; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterQualifiedIdent(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitQualifiedIdent(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitQualifiedIdent(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public QualifiedIdentContext qualifiedIdent() {
		QualifiedIdentContext _localctx = new QualifiedIdentContext(Context, State);
		EnterRule(_localctx, 18, RULE_qualifiedIdent);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 145;
			Match(IDENT);
			State = 148;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 146;
				Match(T__8);
				State = 147;
				Match(IDENT);
				}
				}
				State = 150;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==T__8 );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class ArgListContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ArgContext[] arg() {
			return GetRuleContexts<ArgContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArgContext arg(int i) {
			return GetRuleContext<ArgContext>(i);
		}
		public ArgListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_argList; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterArgList(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitArgList(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArgList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgListContext argList() {
		ArgListContext _localctx = new ArgListContext(Context, State);
		EnterRule(_localctx, 20, RULE_argList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 152;
			arg();
			State = 157;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__6) {
				{
				{
				State = 153;
				Match(T__6);
				State = 154;
				arg();
				}
				}
				State = 159;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class ArgContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ColumnAliasContext columnAlias() {
			return GetRuleContext<ColumnAliasContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArithmeticExprContext arithmeticExpr() {
			return GetRuleContext<ArithmeticExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionCallContext functionCall() {
			return GetRuleContext<FunctionCallContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CaseExprContext caseExpr() {
			return GetRuleContext<CaseExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NamedArgContext namedArg() {
			return GetRuleContext<NamedArgContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ComparisonContext comparison() {
			return GetRuleContext<ComparisonContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PipeExprContext pipeExpr() {
			return GetRuleContext<PipeExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LambdaExprContext lambdaExpr() {
			return GetRuleContext<LambdaExprContext>(0);
		}
		public ArgContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arg; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterArg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitArg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArg(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgContext arg() {
		ArgContext _localctx = new ArgContext(Context, State);
		EnterRule(_localctx, 22, RULE_arg);
		try {
			State = 173;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 160;
				columnAlias();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 161;
				arithmeticExpr();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 162;
				functionCall();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 163;
				caseExpr();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 164;
				expr();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 165;
				namedArg();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 166;
				comparison();
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 167;
				pipeExpr();
				}
				break;
			case 9:
				EnterOuterAlt(_localctx, 9);
				{
				State = 168;
				lambdaExpr();
				}
				break;
			case 10:
				EnterOuterAlt(_localctx, 10);
				{
				State = 169;
				Match(T__3);
				State = 170;
				pipeExpr();
				State = 171;
				Match(T__4);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class ColumnAliasContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ArithmeticExprContext arithmeticExpr() {
			return GetRuleContext<ArithmeticExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionCallContext functionCall() {
			return GetRuleContext<FunctionCallContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public QualifiedIdentContext qualifiedIdent() {
			return GetRuleContext<QualifiedIdentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] IDENT() { return GetTokens(LqlParser.IDENT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT(int i) {
			return GetToken(LqlParser.IDENT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AS() { return GetToken(LqlParser.AS, 0); }
		public ColumnAliasContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_columnAlias; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterColumnAlias(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitColumnAlias(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitColumnAlias(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ColumnAliasContext columnAlias() {
		ColumnAliasContext _localctx = new ColumnAliasContext(Context, State);
		EnterRule(_localctx, 24, RULE_columnAlias);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 179;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,12,Context) ) {
			case 1:
				{
				State = 175;
				arithmeticExpr();
				}
				break;
			case 2:
				{
				State = 176;
				functionCall();
				}
				break;
			case 3:
				{
				State = 177;
				qualifiedIdent();
				}
				break;
			case 4:
				{
				State = 178;
				Match(IDENT);
				}
				break;
			}
			State = 183;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==AS) {
				{
				State = 181;
				Match(AS);
				State = 182;
				Match(IDENT);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class ArithmeticExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ArithmeticTermContext[] arithmeticTerm() {
			return GetRuleContexts<ArithmeticTermContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArithmeticTermContext arithmeticTerm(int i) {
			return GetRuleContext<ArithmeticTermContext>(i);
		}
		public ArithmeticExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arithmeticExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterArithmeticExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitArithmeticExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArithmeticExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArithmeticExprContext arithmeticExpr() {
		ArithmeticExprContext _localctx = new ArithmeticExprContext(Context, State);
		EnterRule(_localctx, 26, RULE_arithmeticExpr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 185;
			arithmeticTerm();
			State = 190;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 7168L) != 0)) {
				{
				{
				State = 186;
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 7168L) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 187;
				arithmeticTerm();
				}
				}
				State = 192;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class ArithmeticTermContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ArithmeticFactorContext[] arithmeticFactor() {
			return GetRuleContexts<ArithmeticFactorContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArithmeticFactorContext arithmeticFactor(int i) {
			return GetRuleContext<ArithmeticFactorContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ASTERISK() { return GetTokens(LqlParser.ASTERISK); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASTERISK(int i) {
			return GetToken(LqlParser.ASTERISK, i);
		}
		public ArithmeticTermContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arithmeticTerm; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterArithmeticTerm(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitArithmeticTerm(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArithmeticTerm(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArithmeticTermContext arithmeticTerm() {
		ArithmeticTermContext _localctx = new ArithmeticTermContext(Context, State);
		EnterRule(_localctx, 28, RULE_arithmeticTerm);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 193;
			arithmeticFactor();
			State = 198;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,15,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 194;
					_la = TokenStream.LA(1);
					if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 72057594037952512L) != 0)) ) {
					ErrorHandler.RecoverInline(this);
					}
					else {
						ErrorHandler.ReportMatch(this);
					    Consume();
					}
					State = 195;
					arithmeticFactor();
					}
					} 
				}
				State = 200;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,15,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class ArithmeticFactorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public QualifiedIdentContext qualifiedIdent() {
			return GetRuleContext<QualifiedIdentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(LqlParser.IDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(LqlParser.INT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DECIMAL() { return GetToken(LqlParser.DECIMAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(LqlParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FunctionCallContext functionCall() {
			return GetRuleContext<FunctionCallContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CaseExprContext caseExpr() {
			return GetRuleContext<CaseExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PARAMETER() { return GetToken(LqlParser.PARAMETER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArithmeticExprContext arithmeticExpr() {
			return GetRuleContext<ArithmeticExprContext>(0);
		}
		public ArithmeticFactorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arithmeticFactor; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterArithmeticFactor(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitArithmeticFactor(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArithmeticFactor(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArithmeticFactorContext arithmeticFactor() {
		ArithmeticFactorContext _localctx = new ArithmeticFactorContext(Context, State);
		EnterRule(_localctx, 30, RULE_arithmeticFactor);
		try {
			State = 213;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,16,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 201;
				qualifiedIdent();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 202;
				Match(IDENT);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 203;
				Match(INT);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 204;
				Match(DECIMAL);
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 205;
				Match(STRING);
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 206;
				functionCall();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 207;
				caseExpr();
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 208;
				Match(PARAMETER);
				}
				break;
			case 9:
				EnterOuterAlt(_localctx, 9);
				{
				State = 209;
				Match(T__3);
				State = 210;
				arithmeticExpr();
				State = 211;
				Match(T__4);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class FunctionCallContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(LqlParser.IDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArgListContext argList() {
			return GetRuleContext<ArgListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DISTINCT() { return GetToken(LqlParser.DISTINCT, 0); }
		public FunctionCallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionCall; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterFunctionCall(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitFunctionCall(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionCall(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionCallContext functionCall() {
		FunctionCallContext _localctx = new FunctionCallContext(Context, State);
		EnterRule(_localctx, 32, RULE_functionCall);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 215;
			Match(IDENT);
			State = 216;
			Match(T__3);
			State = 221;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 89790521966329936L) != 0)) {
				{
				State = 218;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==DISTINCT) {
					{
					State = 217;
					Match(DISTINCT);
					}
				}

				State = 220;
				argList();
				}
			}

			State = 223;
			Match(T__4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class NamedArgContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(LqlParser.IDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ON() { return GetToken(LqlParser.ON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ComparisonContext comparison() {
			return GetRuleContext<ComparisonContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprContext logicalExpr() {
			return GetRuleContext<LogicalExprContext>(0);
		}
		public NamedArgContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_namedArg; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterNamedArg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitNamedArg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNamedArg(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NamedArgContext namedArg() {
		NamedArgContext _localctx = new NamedArgContext(Context, State);
		EnterRule(_localctx, 34, RULE_namedArg);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 225;
			_la = TokenStream.LA(1);
			if ( !(_la==ON || _la==IDENT) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 226;
			Match(T__1);
			State = 229;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,19,Context) ) {
			case 1:
				{
				State = 227;
				comparison();
				}
				break;
			case 2:
				{
				State = 228;
				logicalExpr();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class LogicalExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AndExprContext[] andExpr() {
			return GetRuleContexts<AndExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public AndExprContext andExpr(int i) {
			return GetRuleContext<AndExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] OR() { return GetTokens(LqlParser.OR); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OR(int i) {
			return GetToken(LqlParser.OR, i);
		}
		public LogicalExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logicalExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterLogicalExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitLogicalExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLogicalExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LogicalExprContext logicalExpr() {
		LogicalExprContext _localctx = new LogicalExprContext(Context, State);
		EnterRule(_localctx, 36, RULE_logicalExpr);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 231;
			andExpr();
			State = 236;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,20,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 232;
					Match(OR);
					State = 233;
					andExpr();
					}
					} 
				}
				State = 238;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,20,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class AndExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AtomicExprContext[] atomicExpr() {
			return GetRuleContexts<AtomicExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public AtomicExprContext atomicExpr(int i) {
			return GetRuleContext<AtomicExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] AND() { return GetTokens(LqlParser.AND); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AND(int i) {
			return GetToken(LqlParser.AND, i);
		}
		public AndExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_andExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterAndExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitAndExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAndExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AndExprContext andExpr() {
		AndExprContext _localctx = new AndExprContext(Context, State);
		EnterRule(_localctx, 38, RULE_andExpr);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 239;
			atomicExpr();
			State = 244;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,21,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 240;
					Match(AND);
					State = 241;
					atomicExpr();
					}
					} 
				}
				State = 246;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,21,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class AtomicExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ComparisonContext comparison() {
			return GetRuleContext<ComparisonContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExprContext logicalExpr() {
			return GetRuleContext<LogicalExprContext>(0);
		}
		public AtomicExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_atomicExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterAtomicExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitAtomicExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAtomicExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AtomicExprContext atomicExpr() {
		AtomicExprContext _localctx = new AtomicExprContext(Context, State);
		EnterRule(_localctx, 40, RULE_atomicExpr);
		try {
			State = 252;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,22,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 247;
				comparison();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 248;
				Match(T__3);
				State = 249;
				logicalExpr();
				State = 250;
				Match(T__4);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class ComparisonContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ArithmeticExprContext[] arithmeticExpr() {
			return GetRuleContexts<ArithmeticExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArithmeticExprContext arithmeticExpr(int i) {
			return GetRuleContext<ArithmeticExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ComparisonOpContext comparisonOp() {
			return GetRuleContext<ComparisonOpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public QualifiedIdentContext[] qualifiedIdent() {
			return GetRuleContexts<QualifiedIdentContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public QualifiedIdentContext qualifiedIdent(int i) {
			return GetRuleContext<QualifiedIdentContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(LqlParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] IDENT() { return GetTokens(LqlParser.IDENT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT(int i) {
			return GetToken(LqlParser.IDENT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(LqlParser.INT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DECIMAL() { return GetToken(LqlParser.DECIMAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] PARAMETER() { return GetTokens(LqlParser.PARAMETER); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PARAMETER(int i) {
			return GetToken(LqlParser.PARAMETER, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public OrderDirectionContext orderDirection() {
			return GetRuleContext<OrderDirectionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExistsExprContext existsExpr() {
			return GetRuleContext<ExistsExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NullCheckExprContext nullCheckExpr() {
			return GetRuleContext<NullCheckExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public InExprContext inExpr() {
			return GetRuleContext<InExprContext>(0);
		}
		public ComparisonContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_comparison; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterComparison(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitComparison(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitComparison(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ComparisonContext comparison() {
		ComparisonContext _localctx = new ComparisonContext(Context, State);
		EnterRule(_localctx, 42, RULE_comparison);
		int _la;
		try {
			State = 307;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,29,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 254;
				arithmeticExpr();
				State = 255;
				comparisonOp();
				State = 256;
				arithmeticExpr();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 258;
				qualifiedIdent();
				State = 259;
				comparisonOp();
				State = 266;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,23,Context) ) {
				case 1:
					{
					State = 260;
					qualifiedIdent();
					}
					break;
				case 2:
					{
					State = 261;
					Match(STRING);
					}
					break;
				case 3:
					{
					State = 262;
					Match(IDENT);
					}
					break;
				case 4:
					{
					State = 263;
					Match(INT);
					}
					break;
				case 5:
					{
					State = 264;
					Match(DECIMAL);
					}
					break;
				case 6:
					{
					State = 265;
					Match(PARAMETER);
					}
					break;
				}
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 268;
				Match(IDENT);
				State = 269;
				comparisonOp();
				State = 276;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,24,Context) ) {
				case 1:
					{
					State = 270;
					qualifiedIdent();
					}
					break;
				case 2:
					{
					State = 271;
					Match(STRING);
					}
					break;
				case 3:
					{
					State = 272;
					Match(IDENT);
					}
					break;
				case 4:
					{
					State = 273;
					Match(INT);
					}
					break;
				case 5:
					{
					State = 274;
					Match(DECIMAL);
					}
					break;
				case 6:
					{
					State = 275;
					Match(PARAMETER);
					}
					break;
				}
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 278;
				Match(PARAMETER);
				State = 279;
				comparisonOp();
				State = 286;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,25,Context) ) {
				case 1:
					{
					State = 280;
					qualifiedIdent();
					}
					break;
				case 2:
					{
					State = 281;
					Match(STRING);
					}
					break;
				case 3:
					{
					State = 282;
					Match(IDENT);
					}
					break;
				case 4:
					{
					State = 283;
					Match(INT);
					}
					break;
				case 5:
					{
					State = 284;
					Match(DECIMAL);
					}
					break;
				case 6:
					{
					State = 285;
					Match(PARAMETER);
					}
					break;
				}
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 288;
				qualifiedIdent();
				State = 290;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==ASC || _la==DESC) {
					{
					State = 289;
					orderDirection();
					}
				}

				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 292;
				Match(IDENT);
				State = 294;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==ASC || _la==DESC) {
					{
					State = 293;
					orderDirection();
					}
				}

				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 296;
				Match(PARAMETER);
				State = 298;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==ASC || _la==DESC) {
					{
					State = 297;
					orderDirection();
					}
				}

				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 300;
				Match(STRING);
				}
				break;
			case 9:
				EnterOuterAlt(_localctx, 9);
				{
				State = 301;
				Match(INT);
				}
				break;
			case 10:
				EnterOuterAlt(_localctx, 10);
				{
				State = 302;
				Match(DECIMAL);
				}
				break;
			case 11:
				EnterOuterAlt(_localctx, 11);
				{
				State = 303;
				expr();
				}
				break;
			case 12:
				EnterOuterAlt(_localctx, 12);
				{
				State = 304;
				existsExpr();
				}
				break;
			case 13:
				EnterOuterAlt(_localctx, 13);
				{
				State = 305;
				nullCheckExpr();
				}
				break;
			case 14:
				EnterOuterAlt(_localctx, 14);
				{
				State = 306;
				inExpr();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class ExistsExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EXISTS() { return GetToken(LqlParser.EXISTS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public PipeExprContext pipeExpr() {
			return GetRuleContext<PipeExprContext>(0);
		}
		public ExistsExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_existsExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterExistsExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitExistsExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExistsExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExistsExprContext existsExpr() {
		ExistsExprContext _localctx = new ExistsExprContext(Context, State);
		EnterRule(_localctx, 44, RULE_existsExpr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 309;
			Match(EXISTS);
			State = 310;
			Match(T__3);
			State = 311;
			pipeExpr();
			State = 312;
			Match(T__4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class NullCheckExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public QualifiedIdentContext qualifiedIdent() {
			return GetRuleContext<QualifiedIdentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(LqlParser.IDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PARAMETER() { return GetToken(LqlParser.PARAMETER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IS() { return GetToken(LqlParser.IS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NULL() { return GetToken(LqlParser.NULL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOT() { return GetToken(LqlParser.NOT, 0); }
		public NullCheckExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_nullCheckExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterNullCheckExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitNullCheckExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNullCheckExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NullCheckExprContext nullCheckExpr() {
		NullCheckExprContext _localctx = new NullCheckExprContext(Context, State);
		EnterRule(_localctx, 46, RULE_nullCheckExpr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 317;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,30,Context) ) {
			case 1:
				{
				State = 314;
				qualifiedIdent();
				}
				break;
			case 2:
				{
				State = 315;
				Match(IDENT);
				}
				break;
			case 3:
				{
				State = 316;
				Match(PARAMETER);
				}
				break;
			}
			{
			State = 319;
			Match(IS);
			State = 321;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==NOT) {
				{
				State = 320;
				Match(NOT);
				}
			}

			State = 323;
			Match(NULL);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class InExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IN() { return GetToken(LqlParser.IN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public QualifiedIdentContext qualifiedIdent() {
			return GetRuleContext<QualifiedIdentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(LqlParser.IDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PARAMETER() { return GetToken(LqlParser.PARAMETER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public PipeExprContext pipeExpr() {
			return GetRuleContext<PipeExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArgListContext argList() {
			return GetRuleContext<ArgListContext>(0);
		}
		public InExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_inExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterInExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitInExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public InExprContext inExpr() {
		InExprContext _localctx = new InExprContext(Context, State);
		EnterRule(_localctx, 48, RULE_inExpr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 328;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,32,Context) ) {
			case 1:
				{
				State = 325;
				qualifiedIdent();
				}
				break;
			case 2:
				{
				State = 326;
				Match(IDENT);
				}
				break;
			case 3:
				{
				State = 327;
				Match(PARAMETER);
				}
				break;
			}
			State = 330;
			Match(IN);
			State = 331;
			Match(T__3);
			State = 334;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,33,Context) ) {
			case 1:
				{
				State = 332;
				pipeExpr();
				}
				break;
			case 2:
				{
				State = 333;
				argList();
				}
				break;
			}
			State = 336;
			Match(T__4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class CaseExprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CASE() { return GetToken(LqlParser.CASE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode END() { return GetToken(LqlParser.END, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public WhenClauseContext[] whenClause() {
			return GetRuleContexts<WhenClauseContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public WhenClauseContext whenClause(int i) {
			return GetRuleContext<WhenClauseContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELSE() { return GetToken(LqlParser.ELSE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public CaseResultContext caseResult() {
			return GetRuleContext<CaseResultContext>(0);
		}
		public CaseExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_caseExpr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterCaseExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitCaseExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCaseExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CaseExprContext caseExpr() {
		CaseExprContext _localctx = new CaseExprContext(Context, State);
		EnterRule(_localctx, 50, RULE_caseExpr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 338;
			Match(CASE);
			State = 340;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 339;
				whenClause();
				}
				}
				State = 342;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==WHEN );
			State = 346;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ELSE) {
				{
				State = 344;
				Match(ELSE);
				State = 345;
				caseResult();
				}
			}

			State = 348;
			Match(END);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class WhenClauseContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WHEN() { return GetToken(LqlParser.WHEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ComparisonContext comparison() {
			return GetRuleContext<ComparisonContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode THEN() { return GetToken(LqlParser.THEN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public CaseResultContext caseResult() {
			return GetRuleContext<CaseResultContext>(0);
		}
		public WhenClauseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_whenClause; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterWhenClause(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitWhenClause(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitWhenClause(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public WhenClauseContext whenClause() {
		WhenClauseContext _localctx = new WhenClauseContext(Context, State);
		EnterRule(_localctx, 52, RULE_whenClause);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 350;
			Match(WHEN);
			State = 351;
			comparison();
			State = 352;
			Match(THEN);
			State = 353;
			caseResult();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class CaseResultContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ArithmeticExprContext arithmeticExpr() {
			return GetRuleContext<ArithmeticExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ComparisonContext comparison() {
			return GetRuleContext<ComparisonContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public QualifiedIdentContext qualifiedIdent() {
			return GetRuleContext<QualifiedIdentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENT() { return GetToken(LqlParser.IDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(LqlParser.INT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DECIMAL() { return GetToken(LqlParser.DECIMAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(LqlParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PARAMETER() { return GetToken(LqlParser.PARAMETER, 0); }
		public CaseResultContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_caseResult; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterCaseResult(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitCaseResult(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCaseResult(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CaseResultContext caseResult() {
		CaseResultContext _localctx = new CaseResultContext(Context, State);
		EnterRule(_localctx, 54, RULE_caseResult);
		try {
			State = 363;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,36,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 355;
				arithmeticExpr();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 356;
				comparison();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 357;
				qualifiedIdent();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 358;
				Match(IDENT);
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 359;
				Match(INT);
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 360;
				Match(DECIMAL);
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 361;
				Match(STRING);
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 362;
				Match(PARAMETER);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class OrderDirectionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASC() { return GetToken(LqlParser.ASC, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DESC() { return GetToken(LqlParser.DESC, 0); }
		public OrderDirectionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_orderDirection; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterOrderDirection(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitOrderDirection(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOrderDirection(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OrderDirectionContext orderDirection() {
		OrderDirectionContext _localctx = new OrderDirectionContext(Context, State);
		EnterRule(_localctx, 56, RULE_orderDirection);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 365;
			_la = TokenStream.LA(1);
			if ( !(_la==ASC || _la==DESC) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	internal partial class ComparisonOpContext : ParserRuleContext {
		public ComparisonOpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_comparisonOp; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.EnterComparisonOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILqlListener typedListener = listener as ILqlListener;
			if (typedListener != null) typedListener.ExitComparisonOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILqlVisitor<TResult> typedVisitor = visitor as ILqlVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitComparisonOp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ComparisonOpContext comparisonOp() {
		ComparisonOpContext _localctx = new ComparisonOpContext(Context, State);
		EnterRule(_localctx, 58, RULE_comparisonOp);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 367;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 2064388L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,56,370,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,2,26,7,26,2,27,7,27,2,28,7,28,
		2,29,7,29,1,0,5,0,62,8,0,10,0,12,0,65,9,0,1,0,1,0,1,1,1,1,3,1,71,8,1,1,
		2,1,2,1,2,1,2,1,2,1,3,1,3,1,3,5,3,81,8,3,10,3,12,3,84,9,3,1,4,1,4,1,4,
		3,4,89,8,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,3,4,100,8,4,1,4,1,4,1,4,
		1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,3,4,116,8,4,1,5,3,5,119,8,
		5,1,5,3,5,122,8,5,1,6,1,6,1,6,1,6,1,7,1,7,1,7,1,7,1,8,1,8,1,8,1,8,1,8,
		5,8,137,8,8,10,8,12,8,140,9,8,1,8,1,8,1,8,1,8,1,9,1,9,1,9,4,9,149,8,9,
		11,9,12,9,150,1,10,1,10,1,10,5,10,156,8,10,10,10,12,10,159,9,10,1,11,1,
		11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,3,11,174,8,11,
		1,12,1,12,1,12,1,12,3,12,180,8,12,1,12,1,12,3,12,184,8,12,1,13,1,13,1,
		13,5,13,189,8,13,10,13,12,13,192,9,13,1,14,1,14,1,14,5,14,197,8,14,10,
		14,12,14,200,9,14,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,15,1,
		15,1,15,3,15,214,8,15,1,16,1,16,1,16,3,16,219,8,16,1,16,3,16,222,8,16,
		1,16,1,16,1,17,1,17,1,17,1,17,3,17,230,8,17,1,18,1,18,1,18,5,18,235,8,
		18,10,18,12,18,238,9,18,1,19,1,19,1,19,5,19,243,8,19,10,19,12,19,246,9,
		19,1,20,1,20,1,20,1,20,1,20,3,20,253,8,20,1,21,1,21,1,21,1,21,1,21,1,21,
		1,21,1,21,1,21,1,21,1,21,1,21,3,21,267,8,21,1,21,1,21,1,21,1,21,1,21,1,
		21,1,21,1,21,3,21,277,8,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,3,21,
		287,8,21,1,21,1,21,3,21,291,8,21,1,21,1,21,3,21,295,8,21,1,21,1,21,3,21,
		299,8,21,1,21,1,21,1,21,1,21,1,21,1,21,1,21,3,21,308,8,21,1,22,1,22,1,
		22,1,22,1,22,1,23,1,23,1,23,3,23,318,8,23,1,23,1,23,3,23,322,8,23,1,23,
		1,23,1,24,1,24,1,24,3,24,329,8,24,1,24,1,24,1,24,1,24,3,24,335,8,24,1,
		24,1,24,1,25,1,25,4,25,341,8,25,11,25,12,25,342,1,25,1,25,3,25,347,8,25,
		1,25,1,25,1,26,1,26,1,26,1,26,1,26,1,27,1,27,1,27,1,27,1,27,1,27,1,27,
		1,27,3,27,364,8,27,1,28,1,28,1,29,1,29,1,29,0,0,30,0,2,4,6,8,10,12,14,
		16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,0,5,
		1,0,10,12,2,0,13,14,56,56,2,0,48,48,50,50,1,0,21,22,2,0,2,2,15,20,435,
		0,63,1,0,0,0,2,70,1,0,0,0,4,72,1,0,0,0,6,77,1,0,0,0,8,115,1,0,0,0,10,118,
		1,0,0,0,12,123,1,0,0,0,14,127,1,0,0,0,16,131,1,0,0,0,18,145,1,0,0,0,20,
		152,1,0,0,0,22,173,1,0,0,0,24,179,1,0,0,0,26,185,1,0,0,0,28,193,1,0,0,
		0,30,213,1,0,0,0,32,215,1,0,0,0,34,225,1,0,0,0,36,231,1,0,0,0,38,239,1,
		0,0,0,40,252,1,0,0,0,42,307,1,0,0,0,44,309,1,0,0,0,46,317,1,0,0,0,48,328,
		1,0,0,0,50,338,1,0,0,0,52,350,1,0,0,0,54,363,1,0,0,0,56,365,1,0,0,0,58,
		367,1,0,0,0,60,62,3,2,1,0,61,60,1,0,0,0,62,65,1,0,0,0,63,61,1,0,0,0,63,
		64,1,0,0,0,64,66,1,0,0,0,65,63,1,0,0,0,66,67,5,0,0,1,67,1,1,0,0,0,68,71,
		3,4,2,0,69,71,3,6,3,0,70,68,1,0,0,0,70,69,1,0,0,0,71,3,1,0,0,0,72,73,5,
		1,0,0,73,74,5,50,0,0,74,75,5,2,0,0,75,76,3,6,3,0,76,5,1,0,0,0,77,82,3,
		8,4,0,78,79,5,3,0,0,79,81,3,8,4,0,80,78,1,0,0,0,81,84,1,0,0,0,82,80,1,
		0,0,0,82,83,1,0,0,0,83,7,1,0,0,0,84,82,1,0,0,0,85,86,5,50,0,0,86,88,5,
		4,0,0,87,89,3,20,10,0,88,87,1,0,0,0,88,89,1,0,0,0,89,90,1,0,0,0,90,91,
		5,5,0,0,91,92,5,38,0,0,92,93,5,4,0,0,93,94,3,10,5,0,94,95,5,5,0,0,95,116,
		1,0,0,0,96,97,5,50,0,0,97,99,5,4,0,0,98,100,3,20,10,0,99,98,1,0,0,0,99,
		100,1,0,0,0,100,101,1,0,0,0,101,116,5,5,0,0,102,116,5,50,0,0,103,104,5,
		4,0,0,104,105,3,6,3,0,105,106,5,5,0,0,106,116,1,0,0,0,107,116,3,18,9,0,
		108,116,3,16,8,0,109,116,3,50,25,0,110,116,5,51,0,0,111,116,5,52,0,0,112,
		116,5,56,0,0,113,116,5,53,0,0,114,116,5,49,0,0,115,85,1,0,0,0,115,96,1,
		0,0,0,115,102,1,0,0,0,115,103,1,0,0,0,115,107,1,0,0,0,115,108,1,0,0,0,
		115,109,1,0,0,0,115,110,1,0,0,0,115,111,1,0,0,0,115,112,1,0,0,0,115,113,
		1,0,0,0,115,114,1,0,0,0,116,9,1,0,0,0,117,119,3,12,6,0,118,117,1,0,0,0,
		118,119,1,0,0,0,119,121,1,0,0,0,120,122,3,14,7,0,121,120,1,0,0,0,121,122,
		1,0,0,0,122,11,1,0,0,0,123,124,5,39,0,0,124,125,5,41,0,0,125,126,3,20,
		10,0,126,13,1,0,0,0,127,128,5,40,0,0,128,129,5,41,0,0,129,130,3,20,10,
		0,130,15,1,0,0,0,131,132,5,6,0,0,132,133,5,4,0,0,133,138,5,50,0,0,134,
		135,5,7,0,0,135,137,5,50,0,0,136,134,1,0,0,0,137,140,1,0,0,0,138,136,1,
		0,0,0,138,139,1,0,0,0,139,141,1,0,0,0,140,138,1,0,0,0,141,142,5,5,0,0,
		142,143,5,8,0,0,143,144,3,36,18,0,144,17,1,0,0,0,145,148,5,50,0,0,146,
		147,5,9,0,0,147,149,5,50,0,0,148,146,1,0,0,0,149,150,1,0,0,0,150,148,1,
		0,0,0,150,151,1,0,0,0,151,19,1,0,0,0,152,157,3,22,11,0,153,154,5,7,0,0,
		154,156,3,22,11,0,155,153,1,0,0,0,156,159,1,0,0,0,157,155,1,0,0,0,157,
		158,1,0,0,0,158,21,1,0,0,0,159,157,1,0,0,0,160,174,3,24,12,0,161,174,3,
		26,13,0,162,174,3,32,16,0,163,174,3,50,25,0,164,174,3,8,4,0,165,174,3,
		34,17,0,166,174,3,42,21,0,167,174,3,6,3,0,168,174,3,16,8,0,169,170,5,4,
		0,0,170,171,3,6,3,0,171,172,5,5,0,0,172,174,1,0,0,0,173,160,1,0,0,0,173,
		161,1,0,0,0,173,162,1,0,0,0,173,163,1,0,0,0,173,164,1,0,0,0,173,165,1,
		0,0,0,173,166,1,0,0,0,173,167,1,0,0,0,173,168,1,0,0,0,173,169,1,0,0,0,
		174,23,1,0,0,0,175,180,3,26,13,0,176,180,3,32,16,0,177,180,3,18,9,0,178,
		180,5,50,0,0,179,175,1,0,0,0,179,176,1,0,0,0,179,177,1,0,0,0,179,178,1,
		0,0,0,180,183,1,0,0,0,181,182,5,31,0,0,182,184,5,50,0,0,183,181,1,0,0,
		0,183,184,1,0,0,0,184,25,1,0,0,0,185,190,3,28,14,0,186,187,7,0,0,0,187,
		189,3,28,14,0,188,186,1,0,0,0,189,192,1,0,0,0,190,188,1,0,0,0,190,191,
		1,0,0,0,191,27,1,0,0,0,192,190,1,0,0,0,193,198,3,30,15,0,194,195,7,1,0,
		0,195,197,3,30,15,0,196,194,1,0,0,0,197,200,1,0,0,0,198,196,1,0,0,0,198,
		199,1,0,0,0,199,29,1,0,0,0,200,198,1,0,0,0,201,214,3,18,9,0,202,214,5,
		50,0,0,203,214,5,51,0,0,204,214,5,52,0,0,205,214,5,53,0,0,206,214,3,32,
		16,0,207,214,3,50,25,0,208,214,5,49,0,0,209,210,5,4,0,0,210,211,3,26,13,
		0,211,212,5,5,0,0,212,214,1,0,0,0,213,201,1,0,0,0,213,202,1,0,0,0,213,
		203,1,0,0,0,213,204,1,0,0,0,213,205,1,0,0,0,213,206,1,0,0,0,213,207,1,
		0,0,0,213,208,1,0,0,0,213,209,1,0,0,0,214,31,1,0,0,0,215,216,5,50,0,0,
		216,221,5,4,0,0,217,219,5,25,0,0,218,217,1,0,0,0,218,219,1,0,0,0,219,220,
		1,0,0,0,220,222,3,20,10,0,221,218,1,0,0,0,221,222,1,0,0,0,222,223,1,0,
		0,0,223,224,5,5,0,0,224,33,1,0,0,0,225,226,7,2,0,0,226,229,5,2,0,0,227,
		230,3,42,21,0,228,230,3,36,18,0,229,227,1,0,0,0,229,228,1,0,0,0,230,35,
		1,0,0,0,231,236,3,38,19,0,232,233,5,24,0,0,233,235,3,38,19,0,234,232,1,
		0,0,0,235,238,1,0,0,0,236,234,1,0,0,0,236,237,1,0,0,0,237,37,1,0,0,0,238,
		236,1,0,0,0,239,244,3,40,20,0,240,241,5,23,0,0,241,243,3,40,20,0,242,240,
		1,0,0,0,243,246,1,0,0,0,244,242,1,0,0,0,244,245,1,0,0,0,245,39,1,0,0,0,
		246,244,1,0,0,0,247,253,3,42,21,0,248,249,5,4,0,0,249,250,3,36,18,0,250,
		251,5,5,0,0,251,253,1,0,0,0,252,247,1,0,0,0,252,248,1,0,0,0,253,41,1,0,
		0,0,254,255,3,26,13,0,255,256,3,58,29,0,256,257,3,26,13,0,257,308,1,0,
		0,0,258,259,3,18,9,0,259,266,3,58,29,0,260,267,3,18,9,0,261,267,5,53,0,
		0,262,267,5,50,0,0,263,267,5,51,0,0,264,267,5,52,0,0,265,267,5,49,0,0,
		266,260,1,0,0,0,266,261,1,0,0,0,266,262,1,0,0,0,266,263,1,0,0,0,266,264,
		1,0,0,0,266,265,1,0,0,0,267,308,1,0,0,0,268,269,5,50,0,0,269,276,3,58,
		29,0,270,277,3,18,9,0,271,277,5,53,0,0,272,277,5,50,0,0,273,277,5,51,0,
		0,274,277,5,52,0,0,275,277,5,49,0,0,276,270,1,0,0,0,276,271,1,0,0,0,276,
		272,1,0,0,0,276,273,1,0,0,0,276,274,1,0,0,0,276,275,1,0,0,0,277,308,1,
		0,0,0,278,279,5,49,0,0,279,286,3,58,29,0,280,287,3,18,9,0,281,287,5,53,
		0,0,282,287,5,50,0,0,283,287,5,51,0,0,284,287,5,52,0,0,285,287,5,49,0,
		0,286,280,1,0,0,0,286,281,1,0,0,0,286,282,1,0,0,0,286,283,1,0,0,0,286,
		284,1,0,0,0,286,285,1,0,0,0,287,308,1,0,0,0,288,290,3,18,9,0,289,291,3,
		56,28,0,290,289,1,0,0,0,290,291,1,0,0,0,291,308,1,0,0,0,292,294,5,50,0,
		0,293,295,3,56,28,0,294,293,1,0,0,0,294,295,1,0,0,0,295,308,1,0,0,0,296,
		298,5,49,0,0,297,299,3,56,28,0,298,297,1,0,0,0,298,299,1,0,0,0,299,308,
		1,0,0,0,300,308,5,53,0,0,301,308,5,51,0,0,302,308,5,52,0,0,303,308,3,8,
		4,0,304,308,3,44,22,0,305,308,3,46,23,0,306,308,3,48,24,0,307,254,1,0,
		0,0,307,258,1,0,0,0,307,268,1,0,0,0,307,278,1,0,0,0,307,288,1,0,0,0,307,
		292,1,0,0,0,307,296,1,0,0,0,307,300,1,0,0,0,307,301,1,0,0,0,307,302,1,
		0,0,0,307,303,1,0,0,0,307,304,1,0,0,0,307,305,1,0,0,0,307,306,1,0,0,0,
		308,43,1,0,0,0,309,310,5,26,0,0,310,311,5,4,0,0,311,312,3,6,3,0,312,313,
		5,5,0,0,313,45,1,0,0,0,314,318,3,18,9,0,315,318,5,50,0,0,316,318,5,49,
		0,0,317,314,1,0,0,0,317,315,1,0,0,0,317,316,1,0,0,0,318,319,1,0,0,0,319,
		321,5,28,0,0,320,322,5,29,0,0,321,320,1,0,0,0,321,322,1,0,0,0,322,323,
		1,0,0,0,323,324,5,27,0,0,324,47,1,0,0,0,325,329,3,18,9,0,326,329,5,50,
		0,0,327,329,5,49,0,0,328,325,1,0,0,0,328,326,1,0,0,0,328,327,1,0,0,0,329,
		330,1,0,0,0,330,331,5,30,0,0,331,334,5,4,0,0,332,335,3,6,3,0,333,335,3,
		20,10,0,334,332,1,0,0,0,334,333,1,0,0,0,335,336,1,0,0,0,336,337,5,5,0,
		0,337,49,1,0,0,0,338,340,5,32,0,0,339,341,3,52,26,0,340,339,1,0,0,0,341,
		342,1,0,0,0,342,340,1,0,0,0,342,343,1,0,0,0,343,346,1,0,0,0,344,345,5,
		35,0,0,345,347,3,54,27,0,346,344,1,0,0,0,346,347,1,0,0,0,347,348,1,0,0,
		0,348,349,5,36,0,0,349,51,1,0,0,0,350,351,5,33,0,0,351,352,3,42,21,0,352,
		353,5,34,0,0,353,354,3,54,27,0,354,53,1,0,0,0,355,364,3,26,13,0,356,364,
		3,42,21,0,357,364,3,18,9,0,358,364,5,50,0,0,359,364,5,51,0,0,360,364,5,
		52,0,0,361,364,5,53,0,0,362,364,5,49,0,0,363,355,1,0,0,0,363,356,1,0,0,
		0,363,357,1,0,0,0,363,358,1,0,0,0,363,359,1,0,0,0,363,360,1,0,0,0,363,
		361,1,0,0,0,363,362,1,0,0,0,364,55,1,0,0,0,365,366,7,3,0,0,366,57,1,0,
		0,0,367,368,7,4,0,0,368,59,1,0,0,0,37,63,70,82,88,99,115,118,121,138,150,
		157,173,179,183,190,198,213,218,221,229,236,244,252,266,276,286,290,294,
		298,307,317,321,328,334,342,346,363
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
}
