//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Nimblesite.Lql.Core.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Nimblesite.Lql.Core.Parsing {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ILqlListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class Nimblesite.Lql.CoreBaseListener : ILqlListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] Nimblesite.Lql.CoreParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] Nimblesite.Lql.CoreParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] Nimblesite.Lql.CoreParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] Nimblesite.Lql.CoreParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.letStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLetStmt([NotNull] Nimblesite.Lql.CoreParser.LetStmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.letStmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLetStmt([NotNull] Nimblesite.Lql.CoreParser.LetStmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.pipeExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPipeExpr([NotNull] Nimblesite.Lql.CoreParser.PipeExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.pipeExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPipeExpr([NotNull] Nimblesite.Lql.CoreParser.PipeExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] Nimblesite.Lql.CoreParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] Nimblesite.Lql.CoreParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.windowSpec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWindowSpec([NotNull] Nimblesite.Lql.CoreParser.WindowSpecContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.windowSpec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWindowSpec([NotNull] Nimblesite.Lql.CoreParser.WindowSpecContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.partitionClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPartitionClause([NotNull] Nimblesite.Lql.CoreParser.PartitionClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.partitionClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPartitionClause([NotNull] Nimblesite.Lql.CoreParser.PartitionClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.orderClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrderClause([NotNull] Nimblesite.Lql.CoreParser.OrderClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.orderClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrderClause([NotNull] Nimblesite.Lql.CoreParser.OrderClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.lambdaExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLambdaExpr([NotNull] Nimblesite.Lql.CoreParser.LambdaExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.lambdaExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLambdaExpr([NotNull] Nimblesite.Lql.CoreParser.LambdaExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.qualifiedIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQualifiedIdent([NotNull] Nimblesite.Lql.CoreParser.QualifiedIdentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.qualifiedIdent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQualifiedIdent([NotNull] Nimblesite.Lql.CoreParser.QualifiedIdentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.argList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgList([NotNull] Nimblesite.Lql.CoreParser.ArgListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.argList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgList([NotNull] Nimblesite.Lql.CoreParser.ArgListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.arg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArg([NotNull] Nimblesite.Lql.CoreParser.ArgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.arg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArg([NotNull] Nimblesite.Lql.CoreParser.ArgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.columnAlias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterColumnAlias([NotNull] Nimblesite.Lql.CoreParser.ColumnAliasContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.columnAlias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitColumnAlias([NotNull] Nimblesite.Lql.CoreParser.ColumnAliasContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.arithmeticExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArithmeticExpr([NotNull] Nimblesite.Lql.CoreParser.ArithmeticExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.arithmeticExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArithmeticExpr([NotNull] Nimblesite.Lql.CoreParser.ArithmeticExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.arithmeticTerm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArithmeticTerm([NotNull] Nimblesite.Lql.CoreParser.ArithmeticTermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.arithmeticTerm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArithmeticTerm([NotNull] Nimblesite.Lql.CoreParser.ArithmeticTermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.arithmeticFactor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArithmeticFactor([NotNull] Nimblesite.Lql.CoreParser.ArithmeticFactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.arithmeticFactor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArithmeticFactor([NotNull] Nimblesite.Lql.CoreParser.ArithmeticFactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCall([NotNull] Nimblesite.Lql.CoreParser.FunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCall([NotNull] Nimblesite.Lql.CoreParser.FunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.namedArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamedArg([NotNull] Nimblesite.Lql.CoreParser.NamedArgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.namedArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamedArg([NotNull] Nimblesite.Lql.CoreParser.NamedArgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.logicalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalExpr([NotNull] Nimblesite.Lql.CoreParser.LogicalExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.logicalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalExpr([NotNull] Nimblesite.Lql.CoreParser.LogicalExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.andExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndExpr([NotNull] Nimblesite.Lql.CoreParser.AndExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.andExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndExpr([NotNull] Nimblesite.Lql.CoreParser.AndExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.atomicExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtomicExpr([NotNull] Nimblesite.Lql.CoreParser.AtomicExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.atomicExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtomicExpr([NotNull] Nimblesite.Lql.CoreParser.AtomicExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.comparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparison([NotNull] Nimblesite.Lql.CoreParser.ComparisonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.comparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparison([NotNull] Nimblesite.Lql.CoreParser.ComparisonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.existsExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExistsExpr([NotNull] Nimblesite.Lql.CoreParser.ExistsExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.existsExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExistsExpr([NotNull] Nimblesite.Lql.CoreParser.ExistsExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.nullCheckExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNullCheckExpr([NotNull] Nimblesite.Lql.CoreParser.NullCheckExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.nullCheckExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNullCheckExpr([NotNull] Nimblesite.Lql.CoreParser.NullCheckExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.inExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInExpr([NotNull] Nimblesite.Lql.CoreParser.InExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.inExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInExpr([NotNull] Nimblesite.Lql.CoreParser.InExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.caseExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCaseExpr([NotNull] Nimblesite.Lql.CoreParser.CaseExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.caseExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCaseExpr([NotNull] Nimblesite.Lql.CoreParser.CaseExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.whenClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhenClause([NotNull] Nimblesite.Lql.CoreParser.WhenClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.whenClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhenClause([NotNull] Nimblesite.Lql.CoreParser.WhenClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.caseResult"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCaseResult([NotNull] Nimblesite.Lql.CoreParser.CaseResultContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.caseResult"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCaseResult([NotNull] Nimblesite.Lql.CoreParser.CaseResultContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.orderDirection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrderDirection([NotNull] Nimblesite.Lql.CoreParser.OrderDirectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.orderDirection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrderDirection([NotNull] Nimblesite.Lql.CoreParser.OrderDirectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.comparisonOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparisonOp([NotNull] Nimblesite.Lql.CoreParser.ComparisonOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.comparisonOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparisonOp([NotNull] Nimblesite.Lql.CoreParser.ComparisonOpContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace Nimblesite.Lql.Core.Parsing
