//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Nimblesite.Lql.Core.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Nimblesite.Lql.Core.Parsing {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="Nimblesite.Lql.CoreParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ILqlListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] Nimblesite.Lql.CoreParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] Nimblesite.Lql.CoreParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] Nimblesite.Lql.CoreParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] Nimblesite.Lql.CoreParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.letStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLetStmt([NotNull] Nimblesite.Lql.CoreParser.LetStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.letStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLetStmt([NotNull] Nimblesite.Lql.CoreParser.LetStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.pipeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPipeExpr([NotNull] Nimblesite.Lql.CoreParser.PipeExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.pipeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPipeExpr([NotNull] Nimblesite.Lql.CoreParser.PipeExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] Nimblesite.Lql.CoreParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] Nimblesite.Lql.CoreParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.windowSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWindowSpec([NotNull] Nimblesite.Lql.CoreParser.WindowSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.windowSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWindowSpec([NotNull] Nimblesite.Lql.CoreParser.WindowSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.partitionClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPartitionClause([NotNull] Nimblesite.Lql.CoreParser.PartitionClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.partitionClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPartitionClause([NotNull] Nimblesite.Lql.CoreParser.PartitionClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.orderClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrderClause([NotNull] Nimblesite.Lql.CoreParser.OrderClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.orderClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrderClause([NotNull] Nimblesite.Lql.CoreParser.OrderClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.lambdaExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdaExpr([NotNull] Nimblesite.Lql.CoreParser.LambdaExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.lambdaExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdaExpr([NotNull] Nimblesite.Lql.CoreParser.LambdaExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.qualifiedIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQualifiedIdent([NotNull] Nimblesite.Lql.CoreParser.QualifiedIdentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.qualifiedIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQualifiedIdent([NotNull] Nimblesite.Lql.CoreParser.QualifiedIdentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgList([NotNull] Nimblesite.Lql.CoreParser.ArgListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgList([NotNull] Nimblesite.Lql.CoreParser.ArgListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArg([NotNull] Nimblesite.Lql.CoreParser.ArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArg([NotNull] Nimblesite.Lql.CoreParser.ArgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.columnAlias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColumnAlias([NotNull] Nimblesite.Lql.CoreParser.ColumnAliasContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.columnAlias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColumnAlias([NotNull] Nimblesite.Lql.CoreParser.ColumnAliasContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.arithmeticExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArithmeticExpr([NotNull] Nimblesite.Lql.CoreParser.ArithmeticExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.arithmeticExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArithmeticExpr([NotNull] Nimblesite.Lql.CoreParser.ArithmeticExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.arithmeticTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArithmeticTerm([NotNull] Nimblesite.Lql.CoreParser.ArithmeticTermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.arithmeticTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArithmeticTerm([NotNull] Nimblesite.Lql.CoreParser.ArithmeticTermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.arithmeticFactor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArithmeticFactor([NotNull] Nimblesite.Lql.CoreParser.ArithmeticFactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.arithmeticFactor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArithmeticFactor([NotNull] Nimblesite.Lql.CoreParser.ArithmeticFactorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCall([NotNull] Nimblesite.Lql.CoreParser.FunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCall([NotNull] Nimblesite.Lql.CoreParser.FunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.namedArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamedArg([NotNull] Nimblesite.Lql.CoreParser.NamedArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.namedArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamedArg([NotNull] Nimblesite.Lql.CoreParser.NamedArgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.logicalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalExpr([NotNull] Nimblesite.Lql.CoreParser.LogicalExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.logicalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalExpr([NotNull] Nimblesite.Lql.CoreParser.LogicalExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpr([NotNull] Nimblesite.Lql.CoreParser.AndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpr([NotNull] Nimblesite.Lql.CoreParser.AndExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.atomicExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtomicExpr([NotNull] Nimblesite.Lql.CoreParser.AtomicExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.atomicExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtomicExpr([NotNull] Nimblesite.Lql.CoreParser.AtomicExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparison([NotNull] Nimblesite.Lql.CoreParser.ComparisonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparison([NotNull] Nimblesite.Lql.CoreParser.ComparisonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.existsExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExistsExpr([NotNull] Nimblesite.Lql.CoreParser.ExistsExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.existsExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExistsExpr([NotNull] Nimblesite.Lql.CoreParser.ExistsExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.nullCheckExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNullCheckExpr([NotNull] Nimblesite.Lql.CoreParser.NullCheckExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.nullCheckExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNullCheckExpr([NotNull] Nimblesite.Lql.CoreParser.NullCheckExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.inExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInExpr([NotNull] Nimblesite.Lql.CoreParser.InExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.inExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInExpr([NotNull] Nimblesite.Lql.CoreParser.InExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.caseExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseExpr([NotNull] Nimblesite.Lql.CoreParser.CaseExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.caseExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseExpr([NotNull] Nimblesite.Lql.CoreParser.CaseExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.whenClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhenClause([NotNull] Nimblesite.Lql.CoreParser.WhenClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.whenClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhenClause([NotNull] Nimblesite.Lql.CoreParser.WhenClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.caseResult"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseResult([NotNull] Nimblesite.Lql.CoreParser.CaseResultContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.caseResult"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseResult([NotNull] Nimblesite.Lql.CoreParser.CaseResultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.orderDirection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrderDirection([NotNull] Nimblesite.Lql.CoreParser.OrderDirectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.orderDirection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrderDirection([NotNull] Nimblesite.Lql.CoreParser.OrderDirectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.comparisonOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparisonOp([NotNull] Nimblesite.Lql.CoreParser.ComparisonOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.comparisonOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparisonOp([NotNull] Nimblesite.Lql.CoreParser.ComparisonOpContext context);
}
} // namespace Nimblesite.Lql.Core.Parsing
