//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Nimblesite.Lql.Core.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Nimblesite.Lql.Core.Parsing {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="Nimblesite.Lql.CoreParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ILqlVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] Nimblesite.Lql.CoreParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] Nimblesite.Lql.CoreParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.letStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLetStmt([NotNull] Nimblesite.Lql.CoreParser.LetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.pipeExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPipeExpr([NotNull] Nimblesite.Lql.CoreParser.PipeExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] Nimblesite.Lql.CoreParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.windowSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWindowSpec([NotNull] Nimblesite.Lql.CoreParser.WindowSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.partitionClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPartitionClause([NotNull] Nimblesite.Lql.CoreParser.PartitionClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.orderClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrderClause([NotNull] Nimblesite.Lql.CoreParser.OrderClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.lambdaExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaExpr([NotNull] Nimblesite.Lql.CoreParser.LambdaExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.qualifiedIdent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedIdent([NotNull] Nimblesite.Lql.CoreParser.QualifiedIdentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgList([NotNull] Nimblesite.Lql.CoreParser.ArgListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArg([NotNull] Nimblesite.Lql.CoreParser.ArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.columnAlias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumnAlias([NotNull] Nimblesite.Lql.CoreParser.ColumnAliasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.arithmeticExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArithmeticExpr([NotNull] Nimblesite.Lql.CoreParser.ArithmeticExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.arithmeticTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArithmeticTerm([NotNull] Nimblesite.Lql.CoreParser.ArithmeticTermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.arithmeticFactor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArithmeticFactor([NotNull] Nimblesite.Lql.CoreParser.ArithmeticFactorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCall([NotNull] Nimblesite.Lql.CoreParser.FunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.namedArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamedArg([NotNull] Nimblesite.Lql.CoreParser.NamedArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.logicalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalExpr([NotNull] Nimblesite.Lql.CoreParser.LogicalExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpr([NotNull] Nimblesite.Lql.CoreParser.AndExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.atomicExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtomicExpr([NotNull] Nimblesite.Lql.CoreParser.AtomicExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparison([NotNull] Nimblesite.Lql.CoreParser.ComparisonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.existsExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExistsExpr([NotNull] Nimblesite.Lql.CoreParser.ExistsExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.nullCheckExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullCheckExpr([NotNull] Nimblesite.Lql.CoreParser.NullCheckExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.inExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInExpr([NotNull] Nimblesite.Lql.CoreParser.InExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.caseExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseExpr([NotNull] Nimblesite.Lql.CoreParser.CaseExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.whenClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhenClause([NotNull] Nimblesite.Lql.CoreParser.WhenClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.caseResult"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseResult([NotNull] Nimblesite.Lql.CoreParser.CaseResultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.orderDirection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrderDirection([NotNull] Nimblesite.Lql.CoreParser.OrderDirectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Nimblesite.Lql.CoreParser.comparisonOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparisonOp([NotNull] Nimblesite.Lql.CoreParser.ComparisonOpContext context);
}
} // namespace Nimblesite.Lql.Core.Parsing
